version: "3"

tasks:
  ci:fast:
    env:
      CI: "true"
    cmds:
      - |
        if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
          npm ci
        else
          pnpm install --frozen-lockfile
        fi
      - npm run lint
      - npm run build
      - npm test

  ci:
    cmds:
      - task: ci:fast
